version: '3'

volumes:
  datafiles:

services:
  db:
    container_name: game_data
    image: mysql
    volumes:
      - datafiles:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3306:3306" 
  
  phpadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8000:80"

  mvc:
    container_name: mvc_proj
    build: 
      context: .
      dockerfile: Dockerfile_mvc
    depends_on:
      - db
    ports:
      - "8888:80"
    restart: always
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development

  games:
    container_name: games.api
    build:
      context: .
      dockerfile: Dockerfile_games
    depends_on:
      - db
    ports:
      - "5000:80"
    restart: always
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
      
  genres:
    container_name: genres.api
    build:
      context: .
      dockerfile: Dockerfile_genres
    depends_on:
      - db
    ports:
      - "5002:80"
    restart: always
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development

  cart:
    container_name: cart.api
    build:
      context: .
      dockerfile: Dockerfile_cart
    depends_on:
      - db
    ports:
      - "5004:80"
    restart: always
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development

  order:
    container_name: order.api
    build:
      context: .
      dockerfile: Dockerfile_order
    depends_on:
      - db
    ports:
      - "5006:80"
    restart: always
    environment:
      - DBHOST=db
      - ASPNETCORE_ENVIRONMENT=Development
