FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["./Genre.API/Genre.API.csproj", "Genre.API/"]
RUN dotnet restore "./Genre.API/Genre.API.csproj"
COPY ./Genre.API ./Genre.API
COPY ["/App.Library/App.Library.csproj", "App.Library/"]
COPY ./App.Library/ ./App.Library/

WORKDIR "/src/Genre.API"
RUN dotnet build "Genre.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Genre.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Genre.API.dll"]