FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["./Cart.API/Cart.API.csproj", "Cart.API/"]
RUN dotnet restore "./Cart.API/Cart.API.csproj"
COPY ./Cart.API ./Cart.API
COPY ["/App.Library/App.Library.csproj", "App.Library/"]
COPY ./App.Library/ ./App.Library/

WORKDIR "/src/Cart.API"
RUN dotnet build "Cart.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Cart.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Cart.API.dll"]
