FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["/Games.API/Games.API.csproj", "Games.API/"]
RUN dotnet restore "./Games.API/Games.API.csproj"
COPY ./Games.API ./Games.API
COPY ["/App.Library/App.Library.csproj", "App.Library/"]
COPY ./App.Library/ ./App.Library/
WORKDIR "/src/Games.API"
RUN dotnet build "Games.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Games.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Games.API.dll"]
